[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
extend-select = ["PLR0912", "PLR0913"]

[tool.ruff.lint.per-file-ignores]
"*" = ["UP045"]

[tool.ruff.lint.pylint]
max-branches = 25
max-args = 10
