apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: ancestry-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: SQLite
    type: frser-sqlite-datasource
    uid: ancestry-sqlite
    access: proxy
    url: /data/ancestry.db
    editable: true
    jsonData:
      path: /data/ancestry.db
